# Generated by Django 4.2.6 on 2023-12-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_city', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'db_table': 'oc_lettings_site_profile',
                'managed': False,
            },
        ),
    ]
