version: 2.1
orbs:
  python: circleci/python@2.1.1

jobs:
  test_with-pytest:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run: 
          name: test
          command: python manage.py collectstatic
      - run:
          name: Run tests
          command: coverage run -m pytest
      - run:
          name: Run coverage report
          command: coverage report --fail-under=80
  build:
    docker:
      - image: cimg/base:2022.09
        auth: 
          username: $USERNAME
          password: $PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ . branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build and Push application Docker image
          command: |
            docker build -t antho78780/circleci-docker-example:latest .
            echo $PASSWORD | docker login -u $USERNAME --password-stdin
            docker push antho78780/circleci-docker-example:latest  
  deploy:
    docker:
    - image: cimg/base:2022.09
    steps:
      - checkout
      - run:
          name: deploy img
          command: curl https://api.render.com/deploy/srv-clogd6h46foc73a0bbn0?key=eg0zs3WiYow
    

workflows:
  test:
    jobs:
      - test_with-pytest
      - build:
          context: authentications
          requires:
            - test_with-pytest
          filters:
            branches:
              only:
                - master
      - deploy: 
          requires:
            - build
