version: 2.1
orbs:
  python: circleci/python@2.1.1

jobs:
  test_with-pytest:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: coverage run -m pytest
      - run:
          name: Run coverage report
          command: coverage report --fail-under=80
  build:
    docker:
      - image: cimg/base:2023.04
        auth: 
          username: $USERNAME
          password: $PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ . branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build and Push application Docker image
          command: |
            docker build -t antho78780/letting_test:latest .
            echo $PASSWORD | docker login -u $USERNAME --password-stdin
            docker push antho78780/letting_test:latest  
  deploy:
    docker:
    - image: cimg/base:2023.04
    steps:
      - checkout
      - run:
          name: deploy img
          command: curl https://api.render.com/deploy/srv-clrhubbh3k0c73aj5iqg?key=EzUtgo2hl_s
    

workflows:
  test:
    jobs:
      - test_with-pytest
      - build:
          context: authentications
          requires:
            - test_with-pytest
          filters:
            branches:
              only:
                - master
      - deploy: 
          requires:
            - build
